package cloudoc.glucose;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Breath implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "press")
   private java.lang.Float press;
   @org.kie.api.definition.type.Label(value = "ahi")
   private java.lang.Float ahi;
   private java.lang.Float wear_time;
   @org.kie.api.definition.type.Label(value = "min_spo2")
   private java.lang.Float min_spo2;
   @org.kie.api.definition.type.Label(value = "bmi")
   private java.lang.Float bmi;

   public Breath()
   {
   }

   public java.lang.Float getPress()
   {
      return this.press;
   }

   public void setPress(java.lang.Float press)
   {
      this.press = press;
   }

   public java.lang.Float getAhi()
   {
      return this.ahi;
   }

   public void setAhi(java.lang.Float ahi)
   {
      this.ahi = ahi;
   }

   public java.lang.Float getWear_time()
   {
      return this.wear_time;
   }

   public void setWear_time(java.lang.Float wear_time)
   {
      this.wear_time = wear_time;
   }

   public java.lang.Float getMin_spo2()
   {
      return this.min_spo2;
   }

   public void setMin_spo2(java.lang.Float min_spo2)
   {
      this.min_spo2 = min_spo2;
   }

   public java.lang.Float getBmi()
   {
      return this.bmi;
   }

   public void setBmi(java.lang.Float bmi)
   {
      this.bmi = bmi;
   }

   public Breath(java.lang.Float press, java.lang.Float ahi,
         java.lang.Float wear_time, java.lang.Float min_spo2,
         java.lang.Float bmi)
   {
      this.press = press;
      this.ahi = ahi;
      this.wear_time = wear_time;
      this.min_spo2 = min_spo2;
      this.bmi = bmi;
   }

}