package cloudoc.glucose;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Condition implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("code")
   private java.lang.String code;

   @org.kie.api.definition.type.Label(value = "\u5206\u7EC4")
   private java.lang.String group;

   public Condition()
   {
   }

   public java.lang.String getCode()
   {
      return this.code;
   }

   public void setCode(java.lang.String code)
   {
      this.code = code;
   }

   public java.lang.String getGroup()
   {
      return this.group;
   }

   public void setGroup(java.lang.String group)
   {
      this.group = group;
   }

   public Condition(java.lang.String code, java.lang.String group)
   {
      this.code = code;
      this.group = group;
   }

}