package cloudoc.glucose;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Emr implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("???cm?")
   private java.lang.Integer height;
   @org.kie.api.definition.type.Label("??")
   private java.lang.Float weight;
   @org.kie.api.definition.type.Label("????")
   private java.lang.Float bmi;
   @org.kie.api.definition.type.Label("??????")
   private java.lang.Integer sport_time;

   @org.kie.api.definition.type.Label("???????????")
   private java.lang.Float hba1c;

   @org.kie.api.definition.type.Label("??????")
   private java.lang.Integer drink;

   @org.kie.api.definition.type.Label("????")
   private java.lang.Boolean smoke;

   public Emr()
   {
   }

   public java.lang.Integer getHeight()
   {
      return this.height;
   }

   public void setHeight(java.lang.Integer height)
   {
      this.height = height;
   }

   public java.lang.Float getWeight()
   {
      return this.weight;
   }

   public void setWeight(java.lang.Float weight)
   {
      this.weight = weight;
   }

   public java.lang.Float getBmi()
   {
      return this.bmi;
   }

   public void setBmi(java.lang.Float bmi)
   {
      this.bmi = bmi;
   }

   public java.lang.Integer getSport_time()
   {
      return this.sport_time;
   }

   public void setSport_time(java.lang.Integer sport_time)
   {
      this.sport_time = sport_time;
   }

   public java.lang.Float getHba1c()
   {
      return this.hba1c;
   }

   public void setHba1c(java.lang.Float hba1c)
   {
      this.hba1c = hba1c;
   }

   public java.lang.Integer getDrink()
   {
      return this.drink;
   }

   public void setDrink(java.lang.Integer drink)
   {
      this.drink = drink;
   }

   public java.lang.Boolean getSmoke()
   {
      return this.smoke;
   }

   public void setSmoke(java.lang.Boolean smoke)
   {
      this.smoke = smoke;
   }

   public Emr(java.lang.Integer height, java.lang.Float weight,
         java.lang.Float bmi, java.lang.Integer sport_time,
         java.lang.Float hba1c, java.lang.Integer drink, java.lang.Boolean smoke)
   {
      this.height = height;
      this.weight = weight;
      this.bmi = bmi;
      this.sport_time = sport_time;
      this.hba1c = hba1c;
      this.drink = drink;
      this.smoke = smoke;
   }

}