package cloudoc.glucose;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Medicine implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "\u6BCF\u65E5\u80F0\u5C9B\u7D20\u6CE8\u5C04\u91CF")
   private java.lang.Integer insulineCount;
   @org.kie.api.definition.type.Label(value = "\u662F\u5426\u6CE8\u5C04\u80F0\u5C9B\u7D20")
   private java.lang.Boolean insuline;
   @org.kie.api.definition.type.Label(value = "\u662F\u5426\u53E3\u670D\u964D\u538B\u836F")
   private java.lang.Boolean antidiabetic;

   public Medicine()
   {
   }

   public java.lang.Integer getInsulineCount()
   {
      return this.insulineCount;
   }

   public void setInsulineCount(java.lang.Integer insulineCount)
   {
      this.insulineCount = insulineCount;
   }

   public java.lang.Boolean getInsuline()
   {
      return this.insuline;
   }

   public void setInsuline(java.lang.Boolean insuline)
   {
      this.insuline = insuline;
   }

   public java.lang.Boolean getAntidiabetic()
   {
      return this.antidiabetic;
   }

   public void setAntidiabetic(java.lang.Boolean antidiabetic)
   {
      this.antidiabetic = antidiabetic;
   }

   public Medicine(java.lang.Integer insulineCount,
         java.lang.Boolean insuline, java.lang.Boolean antidiabetic)
   {
      this.insulineCount = insulineCount;
      this.insuline = insuline;
      this.antidiabetic = antidiabetic;
   }

}