package cloudoc.glucose;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Patient implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("???")
   private java.lang.Boolean isDiabetes;
   @org.kie.api.definition.type.Label("???")
   private java.lang.Boolean isHypertension;
   @org.kie.api.definition.type.Label("?????")
   private java.lang.Integer dm_type;

   @org.kie.api.definition.type.Label("???")
   private java.lang.Boolean isAcs;

   public Patient()
   {
   }

   public java.lang.Boolean getIsDiabetes()
   {
      return this.isDiabetes;
   }

   public void setIsDiabetes(java.lang.Boolean isDiabetes)
   {
      this.isDiabetes = isDiabetes;
   }

   public java.lang.Boolean getIsHypertension()
   {
      return this.isHypertension;
   }

   public void setIsHypertension(java.lang.Boolean isHypertension)
   {
      this.isHypertension = isHypertension;
   }

   public java.lang.Integer getDm_type()
   {
      return this.dm_type;
   }

   public void setDm_type(java.lang.Integer dm_type)
   {
      this.dm_type = dm_type;
   }

   public java.lang.Boolean getIsAcs()
   {
      return this.isAcs;
   }

   public void setIsAcs(java.lang.Boolean isAcs)
   {
      this.isAcs = isAcs;
   }

   public Patient(java.lang.Boolean isDiabetes, java.lang.Boolean isHypertension,
         java.lang.Integer dm_type, java.lang.Boolean isAcs)
   {
      this.isDiabetes = isDiabetes;
      this.isHypertension = isHypertension;
      this.dm_type = dm_type;
      this.isAcs = isAcs;
   }

}