package cloudoc.glucose;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Record implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("glucose value")
   private java.lang.Float value;
   @org.kie.api.definition.type.Label("measure point")
   private java.lang.Integer acktype;

   @org.kie.api.definition.type.Label("level")
   private Integer level;

   public Record()
   {
   }

   public java.lang.Float getValue()
   {
      return this.value;
   }

   public void setValue(java.lang.Float value)
   {
      this.value = value;
   }

   public java.lang.Integer getAcktype()
   {
      return this.acktype;
   }

   public void setAcktype(java.lang.Integer acktype)
   {
      this.acktype = acktype;
   }

   public java.lang.Integer getLevel()
   {
      return this.level;
   }

   public void setLevel(java.lang.Integer level)
   {
      this.level = level;
   }

   public Record(java.lang.Float value, java.lang.Integer acktype,
         java.lang.Integer level)
   {
      this.value = value;
      this.acktype = acktype;
      this.level = level;
   }

}